### ISSUE TITLE
Worker doesn't compile with typescript 1.8.10

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/docs-v7#621]
I'm using {N} 2.4.2 with TS 1.8.10.

When I use Worker feature, I get a signature issue with postMessage method in the worker file - it's a ts file.

I then added the following in my references.d.ts file

`/// <reference path="./node_modules/tns-core-modules/webworker.es2016.d.ts" />`

That cleared the signature issue in the editor - but when I compile, I get a duplicate Worker error.

`Found peer TypeScript 1.8.10
node_modules/tns-core-modules/webworker.es2016.d.ts(5,15): error TS2300: Duplicate identifier 'Worker'.

node_modules/tns-core-modules/webworker.es2016.d.ts(27,24): error TS2503: Cannot find namespace 'Worker'.

node_modules/tns-core-modules/webworker.es2016.d.ts(32,22): error TS2503: Cannot find namespace 'Worker'.
node_modules/tns-core-modules/webworker.es2016.d.ts(38,13): error TS2403: Subsequent variable declarations must have the
 same type.  Variable 'self' must be of type 'Window', but here has type 'any'.
node_modules/tns-core-modules/webworker.es2016.d.ts(43,25): error TS2503: Cannot find namespace 'Worker'.
node_modules/tns-core-modules/webworker.es2016.d.ts(48,23): error TS2503: Cannot find namespace 'Worker'.
node_modules/tns-core-modules/webworker.es2016.d.ts(53,23): error TS2503: Cannot find namespace 'Worker'.
node_modules/tns-core-modules/webworker.es2016.d.ts(65,19): error TS2300: Duplicate identifier 'Worker'.

node_modules/typescript/lib/lib.d.ts(16138,11): error TS2300: Duplicate identifier 'Worker'.

node_modules/typescript/lib/lib.d.ts(16147,13): error TS2300: Duplicate identifier 'Worker'.

TypeScript compiler failed with exit code 1`.

Help - I'm stopped!

**Comment by NickIliev** [comment]
Hey @erjdriver I tried to reproduce your case but to no avail. Are you still experiencing this in N 2.5.X ?
For your convenience here is the package.json of the test applicaiton I've used

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.workersTS",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
}

```

**Comment by erjdriver** [comment]
Thanks for getting back...it works fine now I think since NS 2.5.

Case closed.
